// Generated by CoffeeScript 2.3.2
(function() {
  // CoffeeScript - BlogMaker

  //Load onecup files
  eval(onecup.import());

  //For CSS see CSS.coffee

  //Store Blog Info Globally
  window.blog = {};

  window.blog.blogPosts = [];

  window.BlogMaker = (function() {
    //Class to manipulate blogs
    class BlogMaker {
      static addBlog(title, date, imgs, text, author) {
        window.blog.blogPosts.push(new BlogPost(title, date, imgs, text, author));
      }

      //This shouldn't be used - Only for testing 
      static generateTempBlogPost() {
        var data;
        data = "Hey guys! This is our first blogpost! :D So yesterday at 12/16/18 from 9AM-4PM we went to Strait Jesuit for a FRC workshop since it's our first time doing FRC. We learned a variety of things like <!Break>-Try to make the robot specialize in one task rather than many tasks<!> <!Break>-Reduce the degrees of freedom (Ways the robot can move)<!> <!Break>-Don't try to make the robot move sideways<!> <!Break>-Use a tank drive system<!> <!Break>-Try to minimize having parts outside of the bumper frame<!> Overall, we really enjoyed the experience!";
        return this.addBlog("STRAIT JESUIT FRC WORKSHOP", new window.Date(12, 17, 2018), [new CustomImage("imgs/roboticsstraitjesuit2018-2_d600.png", 460, 283)], data, "Jacob Enerio");
      }

    };

    window.Date = (function() {
      
      //Class to store dates
      class Date {
        //Parameter constructor for controlled dates
        constructor(m, d, y) {
          this.year = y;
          this.month = m;
          this.day = d;
        }

        toString() {
          return this.month + "/" + this.day + "/" + this.year;
        }

      };

      Date.year = 2019;

      Date.month = 2;

      Date.day = 1;

      return Date;

    }).call(this);

    window.CustomImage = (function() {
      class CustomImage {
        //Parameter consutrctor for controlled images
        constructor(s, w, h) {
          this.src = s;
          this.width = w;
          this.height = h;
        }

      };

      CustomImage.src = "imgs/roboticsstraitjesuit2018-2_d600.png";

      CustomImage.width = "460";

      CustomImage.height = "283";

      return CustomImage;

    }).call(this);

    window.BlogPost = (function() {
      
      //Class to store blogposts
      class BlogPost {
        //Parameter constructor for controlled blog posts
        constructor(t, d, imgs, text, auth) {
          this.title = t;
          this.date = d;
          this.imgs = imgs;
          this.text = text;
          this.author = auth;
        }

      };

      BlogPost.title = "Blog Number 1";

      BlogPost.date = new Date();

      //All image sources for images in the blog post
      BlogPost.imgs = [];

      BlogPost.text = "This is a blog post";

      BlogPost.author = "Jacob Enerio";

      return BlogPost;

    }).call(this);

    return BlogMaker;

  }).call(this);

  //@makePosts()

  //---UI RELATED FUNCTIONS---

  //Display a blog post on the website
  ui.makePost = function(blogPost) {
    var splicedText;
    //console.log("Making post")
    splicedText = ui.spliceText(blogPost.text);
    return div(".blogPost", function() {
      var j, len, textData, textDataRef;
      position("relative");
      top("100px");
      height("750px");
      width("500px");
      margin("auto");
      overflow_y("scroll");
      //Title div
      div(function() {
        position("relative");
        font_style("italic");
        font_weight("bold");
        text_decoration("underline");
        return text(blogPost.title);
      });
      //Date div
      div(function() {
        font_style("italic");
        position("relative");
        return text(blogPost.date);
      });
      //Image div
      div(function() {
        position("relative");
        return img({
          src: blogPost.imgs[0].src,
          width: blogPost.imgs[0].width,
          height: blogPost.imgs[0].height
        }, function() {
          display("block");
          margin_left("auto");
          return margin_right("auto");
        });
      });
//Content Div
      for (textDataRef = j = 0, len = splicedText.length; j < len; textDataRef = ++j) {
        textData = splicedText[textDataRef];
        div(function() {
          return text(textData.text);
        });
      }
      return div(function() {
        position("relative");
        font_style("italic");
        text_decoration("underline");
        return text("By " + blogPost.author);
      });
    });
  };

  
  //onecup.refresh()

  //Make blogs posts - Needs to be changed
  ui.makePosts = function() {
    var blogPost, i, j, len, ref, results;
    ref = window.blog.blogPosts;
    results = [];
    for (i = j = 0, len = ref.length; j < len; i = ++j) {
      blogPost = ref[i];
      results.push(ui.makePost(blogPost));
    }
    return results;
  };

  //Check blogging status
  ui.blogging = function() {
    if (window.blog.blogPosts.length === 0) {
      window.BlogMaker.generateTempBlogPost();
    }
    //Make blog posts if we are on blogging page

    //console.log("Making blog post")
    return ui.makePosts();
  };

  //setInterval(ui.blogging,100)
//ui.blogging()

}).call(this);
