// Generated by CoffeeScript 1.12.8
(function() {
  eval(onecup["import"]());

  css(".navBar", function() {
    border_radius("10px");
    border_bottom("4px solid #ffffff");
    padding("10px");
    font_family("Quango");
    color("#008080");
    return position("relative");
  });

  css(".navMenu", function() {
    border_radius("10px");
    border_bottom("4px solid #ffffff");
    border_top("4px solid #ffffff");
    padding("10px");
    font_family("Quango");
    return color("#008080");
  });

  css(".navTitle:hover", function() {
    return text_shadow("0 0 10px #3333ff;");
  });

  css(".navButton", function() {
    font_family("Quango");
    top("50px");
    width("110px");
    height("25px");
    color("#008080");
    position("absolute");
    display("inline-block");
    margin("auto");
    return text_align("center");
  });

  css(".navButton:hover", function() {
    box_shadow("0 0 0 4px #ccffff, 0 0 0 6px #006666");
    return text_shadow("0 0 10px #3333ff");
  });

  css(".dullesButton", function() {
    font_family("Quango");
    top("50px");
    width("110px");
    height("45px");
    color("#008080");
    position("absolute");
    display("inline-block");
    margin("auto");
    return text_align("center");
  });

  css(".dullesButton:hover", function() {
    box_shadow("0 0 0 4px #ccffff, 0 0 0 6px #006666");
    return text_shadow("0 0 10px #3333ff");
  });

  css(".dullesButton2", function() {
    font_family("Quango");
    color("#008080");
    return text_align("center");
  });

  css(".dullesButton2:hover", function() {
    box_shadow("0 0 0 4px #ccffff, 0 0 0 6px #006666");
    return text_shadow("0 0 10px #3333ff");
  });

  css(".blogPost", function() {
    border("4px solid #008080");
    padding("10px");
    box_shadow("0 0 0 8px #ccffff, 0 0 0 12px #006666");
    font_family("Quango");
    return background_color("#F0F0F0");
  });

  css(".menu", function() {
    border("4px solid #008080");
    border_style("inset");
    padding("10px");
    background_color("rgba(0,0,0,1)");
    return transition("all 0.5s ease-out");
  });

  css(".about", function() {
    border("4px solid #008080");
    padding("10px");
    box_shadow("0 0 0 8px #ccffff, 0 0 0 12px #006666");
    font_family("Quango");
    return background_color("#F0F0F0");
  });

  css("#LoginButton:hover", function() {
    transition("all 0s ease-out");
    return text_shadow("0 0 10px #99ffff");
  });

  css(".hover-black", function() {
    return background_color("rgba(0,0,0,0)");
  });

  css(".hover-black:hover", function() {
    return background_color("rgba(0,0,0,.3)");
  });

  css(".hover-black-dark", function() {
    return background_color("rgba(0,0,0,.1)");
  });

  css(".hover-black-dark:hover", function() {
    return background_color("rgba(0,0,0,.4)");
  });

  css(".hover-white", function() {
    return background_color("rgba(255,255,255,0)");
  });

  css(".hover-white:hover", function() {
    return background_color("rgba(255,255,255,.3)");
  });

  css(".hover-red", function() {
    return background_color("rgba(255,0,0,.3)");
  });

  css(".hover-red:hover", function() {
    return background_color("rgba(255,0,0,.7)");
  });

  css(".button", function() {
    return background_color("rgba(255,255,255,.1)");
  });

  css(".button:hover", function() {
    return background_color("rgba(0,0,0,.5)");
  });

  css(".menu-button", function() {
    background_color("rgba(255,255,255,.1)");
    text_align("left");
    padding(20);
    font_size(30);
    color("white");
    width("100%");
    return border("none");
  });

  css(".menu-button:hover", function() {
    return background_color("rgba(0,0,0,.5)");
  });

  css(".hover-fade", function() {
    return opacity(".2");
  });

  css(".hover-fade:hover", function() {
    return opacity("1");
  });

}).call(this);
