// Generated by CoffeeScript 1.12.8
(function() {
  eval(onecup["import"]());

  ui.documents = function() {
    return ui.downloadMenu("Documents", "Documents Navigation", ["files/Interest Meeting Application.docx", "files/Robotics Sponsorship Packet.docx", "files/GitHub Instructions for Dulles Robotics.docx"], ["Interest Meeting Form", "Sponsorship Packet", "GitHub and Android Studio Download Instructions"], window.innerWidth / 2 - 110, 150);
  };

}).call(this);
