// Generated by CoffeeScript 1.12.8
(function() {
  eval(onecup["import"]());

  ui.home = function() {
    return img({
      src: "imgs/RoboticsFlyer.jpeg",
      width: (window.innerWidth - 30) / 3,
      height: 2.5 * window.innerHeight / 3
    }, function() {
      position("relative");
      top("50px");
      display("block");
      margin_left("auto");
      return margin_right("auto");
    });
  };

}).call(this);
