// Generated by CoffeeScript 2.3.2
(function() {
  // CoffeeScript - login

  //Load onecup files
  eval(onecup.import());

  ui.login = function() {
    return ui.stateMenu("Login", "Login Navigation", ["Login", "Register", "Forgot Password"], ["Login", "Register", "Forgot Password"], 35, 150);
  };

}).call(this);
