// Generated by CoffeeScript 2.3.2
(function() {
  // CoffeeScript - media.coffee

  //Load onecup files
  eval(onecup.import());

  //Make a menu
  //Add twitter widget, facebook widget, instagram widget, discord widget, and remind widget
  ui.media = function() {
    ui.stateMenu("Media", "Media Navigation", ["Remind", "Instagram", "Facebook", "Twitter"], ["Remind", "Instagram", "Facebook", "Twitter"], 35, 150);
    return div(".about", function() {
      top("50px");
      width("600px");
      left("50px");
      margin("auto");
      position("relative");
      div(function() {
        position("relative");
        font_style("italic");
        font_weight("bold");
        text_decoration("underline");
        text_align("center");
        return text(ui.menuStates.get("Media"));
      });
      //Sets the div height for widgets
      return div("#mediaHeight", function() {});
    });
  };

  //ui.mediaButton "Discord" , "Discord" , 220 , 45 , window.innerWidth-250, 500 Make discord section for logged in members only

  //Make sure only certain widgets show
  ui.mediaCheck = function() {
    var temp;
    if (ui.state !== "MEDIA") {
      return;
    }
    if (ui.menuStates.get("Media") === "Twitter") {
      if (ui.twitterDiv != null) {
        ui.twitterDiv.style.visibility = "visible";
        ui.twitterDiv.style.position = "absolute";
        ui.twitterDiv.style.width = "560px";
        ui.twitterDiv.style.marginLeft = "auto";
        ui.twitterDiv.style.marginRight = "auto";
        ui.twitterDiv.style.display = "inline-block";
        
        //Set inside div height
        temp = onecup.lookup("#mediaHeight");
        if ((temp != null) && ui.twitterDiv.parentNode !== temp) {
          temp.appendChild(ui.twitterDiv);
        }
        temp.style.height = ui.twitterDiv.style.height;
      }
    } else {
      //Delete twitter div if we aren't on the twitter state
      if (ui.twitterDiv != null) {
        ui.twitterDiv.style.visibility = "hidden";
      }
    }
    if (ui.menuStates.get("Media") === "Facebook") {
      if (ui.facebookDiv != null) {
        ui.facebookDiv.style.visibility = "visible";
        ui.facebookDiv.style.position = "absolute";
        ui.facebookDiv.style.left = "120px";
        ui.facebookDiv.style.marginLeft = "auto";
        ui.facebookDiv.style.marginRight = "auto";
        ui.facebookDiv.style.display = "inline-block";
        
        //Set inside div height
        temp = onecup.lookup("#mediaHeight");
        if ((temp != null) && ui.facebookDiv.parentNode !== temp) {
          temp.appendChild(ui.facebookDiv);
        }
        temp.style.height = "500px";
      }
    } else {
      //Delete facebook div if we aren't on the facebook state
      if (ui.facebookDiv != null) {
        ui.facebookDiv.style.visibility = "hidden";
      }
    }
    if (ui.menuStates.get("Media") === "Instagram") {
      if (ui.instagramDiv != null) {
        ui.instagramDiv.style.visibility = "visible";
        ui.instagramDiv.style.position = "absolute";
        ui.instagramDiv.style.width = "550px";
        //ui.instagramDiv.style.left = "120px"
        ui.instagramDiv.style.marginLeft = "auto";
        ui.instagramDiv.style.marginRight = "auto";
        ui.instagramDiv.style.display = "inline-block";
        
        //Set inside div height
        temp = onecup.lookup("#mediaHeight");
        if ((temp != null) && ui.instagramDiv.parentNode !== temp) {
          temp.appendChild(ui.instagramDiv);
        }
        temp.style.height = ui.instagramDiv.style.height;
      }
    } else {
      //Delete instagram div if we aren't on the instagram state
      if (ui.instagramDiv != null) {
        ui.instagramDiv.style.visibility = "hidden";
      }
    }
    if (ui.menuStates.get("Media") === "Remind") {
      if (ui.remindDiv != null) {
        ui.remindDiv.style.visibility = "visible";
        ui.remindDiv.style.position = "absolute";
        ui.remindDiv.style.width = "550px";
        ui.remindDiv.style.left = "20px";
        ui.remindDiv.style.marginLeft = "auto";
        ui.remindDiv.style.marginRight = "auto";
        ui.remindDiv.style.display = "inline-block";
        
        //Set inside div height
        temp = onecup.lookup("#mediaHeight");
        if ((temp != null) && ui.remindDiv.parentNode !== temp) {
          temp.appendChild(ui.remindDiv);
        }
        return temp.style.height = "320px";
      }
    } else {
      //Delete remind div if we aren't on the remind state
      if (ui.remindDiv != null) {
        return ui.remindDiv.style.visibility = "hidden";
      }
    }
  };

}).call(this);
