// Generated by CoffeeScript 1.12.7
(function() {
  particlesJS.load('particles-js', 'libs/particles.json', function() {
    console.log('callback - particles.js config loaded');
  });

}).call(this);
