// Generated by CoffeeScript 1.12.8
(function() {
  particlesJS.load('particles-js', 'src/particles.json', function() {
    console.log('callback - particles.js config loaded');
  });

}).call(this);
